# Update dependencies

version: 2
updates:
# Update the Github Action  versions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 5
  labels:
  - "dependencies"
  - "automerge"
