name: PR Workflows

# Run action on pull request event
on: [pull_request]

permissions:
  contents: read

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Build the site to verify the PR
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    # checkout to the commit that has been pushed
    - uses: actions/checkout@v7

    - name: Setup Node
      uses: actions/setup-node@v7
      with:
        node-version: 22

    - name: Install node modules
      run: npm ci

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3.2.1
      with:
        hugo-version: '0.160.1'
        extended: true

    - name: Build
      run: |
        hugo --minify
